// <auto-generated />
// Generated by Tools/runtime_map_codegen.py. Do not edit manually.
using System;

namespace ModernRA.Rules
{
    public static class GrayRangeGeneratedData
    {
        public const int GeneratorVersion = 1;
        public const string SourceMapSha256 = "8364ee49943840c0ca1fd4710df01e9879ce87ef4262d57fd17ff3b148e92d63";

        public static RuntimeMapBootstrapData Create()
        {
            return new RuntimeMapBootstrapData
            {
                MapId = "MAP_GRAY_RANGE",
                SizeMeters = new Int2(8000, 8000),
                Spawns = new RuntimeSpawnAnchor[]
                {
                    new RuntimeSpawnAnchor("SPAWN_A", 1, new Int2(1200, 1200), 45, 700, new Int2[] { new Int2(500, 500), new Int2(1900, 500), new Int2(1900, 1900), new Int2(500, 1900) }, new Int2[] { new Int2(2100, 1800), new Int2(1800, 2100) }),
                    new RuntimeSpawnAnchor("SPAWN_B", 2, new Int2(6800, 6800), 225, 700, new Int2[] { new Int2(6100, 6100), new Int2(7500, 6100), new Int2(7500, 7500), new Int2(6100, 7500) }, new Int2[] { new Int2(5900, 6200), new Int2(6200, 5900) }),
                },
                Resources = new RuntimeResourceAnchor[]
                {
                    new RuntimeResourceAnchor("RES_A_I1", "INDUSTRIAL", "MIN_BASE_METALS", new Int2(800, 1700), 60000L, 900, 2, "REGION_HOME_A"),
                    new RuntimeResourceAnchor("RES_A_I2", "INDUSTRIAL", "MIN_BASE_METALS", new Int2(1700, 800), 60000L, 900, 2, "REGION_HOME_A"),
                    new RuntimeResourceAnchor("RES_A_S1", "STRATEGIC", "MIN_MIXED_STRATEGIC", new Int2(1900, 1900), 12000L, 180, 2, "REGION_HOME_A"),
                    new RuntimeResourceAnchor("RES_B_I1", "INDUSTRIAL", "MIN_BASE_METALS", new Int2(7200, 6300), 60000L, 900, 2, "REGION_HOME_B"),
                    new RuntimeResourceAnchor("RES_B_I2", "INDUSTRIAL", "MIN_BASE_METALS", new Int2(6300, 7200), 60000L, 900, 2, "REGION_HOME_B"),
                    new RuntimeResourceAnchor("RES_B_S1", "STRATEGIC", "MIN_MIXED_STRATEGIC", new Int2(6100, 6100), 12000L, 180, 2, "REGION_HOME_B"),
                    new RuntimeResourceAnchor("RES_MID_I1", "INDUSTRIAL", "MIN_BASE_METALS", new Int2(3400, 4000), 60000L, 900, 2, "REGION_CENTER"),
                    new RuntimeResourceAnchor("RES_MID_I2", "INDUSTRIAL", "MIN_BASE_METALS", new Int2(4600, 4000), 60000L, 900, 2, "REGION_CENTER"),
                },
                StrategicSites = new RuntimeStrategicSiteAnchor[]
                {
                    new RuntimeStrategicSiteAnchor("SITE_DATA_CENTER", "DATA_CENTER", new Int2(4000, 4000), "REGION_CENTER"),
                    new RuntimeStrategicSiteAnchor("SITE_RADAR_E", "RADAR", new Int2(5200, 3800), "REGION_EAST"),
                    new RuntimeStrategicSiteAnchor("SITE_RADAR_W", "RADAR", new Int2(2800, 4200), "REGION_WEST"),
                },
                Roads = new RuntimeRoad[]
                {
                    new RuntimeRoad("ROAD_CENTER", new Int2[] { new Int2(1200, 1200), new Int2(3000, 3000), new Int2(4000, 4000), new Int2(5000, 5000), new Int2(6800, 6800) }, 80, 800),
                    new RuntimeRoad("ROAD_EAST", new Int2[] { new Int2(1200, 1200), new Int2(3000, 2600), new Int2(5000, 4600), new Int2(6800, 6800) }, 60, 850),
                    new RuntimeRoad("ROAD_WEST", new Int2[] { new Int2(1200, 1200), new Int2(2600, 3000), new Int2(4000, 4000), new Int2(6200, 5900), new Int2(6800, 6800) }, 60, 850),
                },
                BuildableAreas = new RuntimePolygonArea[]
                {
                    new RuntimePolygonArea("BUILD_A", 1, new Int2[] { new Int2(300, 300), new Int2(2300, 300), new Int2(2300, 2300), new Int2(300, 2300) }),
                    new RuntimePolygonArea("BUILD_B", 2, new Int2[] { new Int2(5700, 5700), new Int2(7700, 5700), new Int2(7700, 7700), new Int2(5700, 7700) }),
                },
                ControlRegions = new RuntimeControlRegion[]
                {
                    new RuntimeControlRegion("REGION_CENTER", new Int2[] { new Int2(2600, 2600), new Int2(5400, 2600), new Int2(5400, 5400), new Int2(2600, 5400) }, new string[] { "REGION_EAST", "REGION_HOME_A", "REGION_HOME_B", "REGION_WEST" }, 2000),
                    new RuntimeControlRegion("REGION_EAST", new Int2[] { new Int2(4000, 2800), new Int2(6200, 2800), new Int2(6200, 5800), new Int2(4000, 5800) }, new string[] { "REGION_CENTER", "REGION_HOME_A", "REGION_HOME_B" }, 1300),
                    new RuntimeControlRegion("REGION_HOME_A", new Int2[] { new Int2(0, 0), new Int2(2600, 0), new Int2(2600, 2600), new Int2(0, 2600) }, new string[] { "REGION_CENTER", "REGION_EAST", "REGION_WEST" }, 1000),
                    new RuntimeControlRegion("REGION_HOME_B", new Int2[] { new Int2(5400, 5400), new Int2(8000, 5400), new Int2(8000, 8000), new Int2(5400, 8000) }, new string[] { "REGION_CENTER", "REGION_EAST", "REGION_WEST" }, 1000),
                    new RuntimeControlRegion("REGION_WEST", new Int2[] { new Int2(1800, 2200), new Int2(4000, 2200), new Int2(4000, 5200), new Int2(1800, 5200) }, new string[] { "REGION_CENTER", "REGION_HOME_A", "REGION_HOME_B" }, 1300),
                },
                RulesetCompatibility = new string[] { "RULESET_ANNIHILATION_STANDARD", "RULESET_CONQUEST_STANDARD" }
            };
        }
    }
}
