import importlib.util
import pathlib
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "Tools" / "run_unity_g1.py"
SPEC = importlib.util.spec_from_file_location("run_unity_g1", MODULE_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)


class UnityG1ProjectSettingsCaptureTests(unittest.TestCase):
    def test_missing_baseline_lists_required_project_settings(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = pathlib.Path(temp_dir)
            (root / "ProjectSettings").mkdir()
            missing = MODULE.missing_versioned_project_settings(root)
            self.assertEqual(set(MODULE.REQUIRED_VERSIONED_PROJECT_SETTINGS), set(missing))

    def test_complete_baseline_has_no_missing_files(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = pathlib.Path(temp_dir)
            settings = root / "ProjectSettings"
            settings.mkdir()
            for name in MODULE.REQUIRED_VERSIONED_PROJECT_SETTINGS:
                (settings / name).write_text("generated by Unity", encoding="utf-8")
            self.assertEqual([], MODULE.missing_versioned_project_settings(root))

    def test_snapshot_copies_only_unversioned_generated_settings(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = pathlib.Path(temp_dir) / "repo"
            artifacts = pathlib.Path(temp_dir) / "artifacts"
            settings = root / "ProjectSettings"
            settings.mkdir(parents=True)
            names = MODULE.REQUIRED_VERSIONED_PROJECT_SETTINGS[:3]
            for index, name in enumerate(names):
                (settings / name).write_text(f"unity-{index}", encoding="utf-8")
            copied = MODULE.snapshot_generated_project_settings(root, artifacts, names)
            self.assertEqual(list(names), copied)
            for index, name in enumerate(names):
                self.assertEqual(
                    f"unity-{index}",
                    (artifacts / "generated-project-settings" / name).read_text(encoding="utf-8"),
                )


if __name__ == "__main__":
    unittest.main()
