<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Packages/com.modernra.rules/Runtime/*.cs" Link="Rules/%(Filename)%(Extension)" />
    <Compile Include="../ModernRA.CommandRunner/PlayerCommandReplayFile.cs" Link="Replay/PlayerCommandReplayFile.cs" />
  </ItemGroup>
</Project>
