#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

GENERATOR_VERSION = 1
TARGET_MAP_ID = "MAP_GRAY_RANGE"


def canonical_bytes(data: Any) -> bytes:
    return json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def canonical_sha256(data: Any) -> str:
    return hashlib.sha256(canonical_bytes(data)).hexdigest()


def cs_string(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def cs_point(point: list[int | float]) -> str:
    return f"new Int2({int(point[0])}, {int(point[1])})"


def cs_points(points: list[list[int | float]]) -> str:
    if not points:
        return "Array.Empty<Int2>()"
    return "new Int2[] { " + ", ".join(cs_point(p) for p in points) + " }"


def cs_strings(values: list[str]) -> str:
    if not values:
        return "Array.Empty<string>()"
    return "new string[] { " + ", ".join(cs_string(v) for v in values) + " }"


def validate_map(data: dict[str, Any]) -> None:
    errors: list[str] = []
    if data.get("map_id") != TARGET_MAP_ID:
        errors.append(f"expected map_id {TARGET_MAP_ID}")
    if data.get("size_m") != [8000, 8000]:
        errors.append("Gray Range runtime profile requires 8000x8000m map")
    spawns = {s.get("team_slot") for s in data.get("spawn_sectors", [])}
    if spawns != {1, 2}:
        errors.append("runtime bootstrap requires exactly team 1 and team 2 spawn sectors")
    road_ids = {r.get("road_id") for r in data.get("roads", [])}
    if "ROAD_CENTER" not in road_ids:
        errors.append("runtime bootstrap requires ROAD_CENTER")
    if "RULESET_ANNIHILATION_STANDARD" not in data.get("ruleset_compatibility", []):
        errors.append("map must support RULESET_ANNIHILATION_STANDARD")
    region_ids = {r.get("region_id") for r in data.get("control_regions", [])}
    for region in data.get("control_regions", []):
        for neighbor in region.get("neighbors", []):
            if neighbor not in region_ids:
                errors.append(f"region {region.get('region_id')} references missing {neighbor}")
    if errors:
        raise ValueError("; ".join(errors))


def generate_source(data: dict[str, Any]) -> str:
    validate_map(data)
    source_hash = canonical_sha256(data)
    lines: list[str] = []
    lines += [
        "// <auto-generated />",
        "// Generated by Tools/runtime_map_codegen.py. Do not edit manually.",
        "using System;",
        "",
        "namespace ModernRA.Rules",
        "{",
        "    public static class GrayRangeGeneratedData",
        "    {",
        f"        public const int GeneratorVersion = {GENERATOR_VERSION};",
        f"        public const string SourceMapSha256 = {cs_string(source_hash)};",
        "",
        "        public static RuntimeMapBootstrapData Create()",
        "        {",
        "            return new RuntimeMapBootstrapData",
        "            {",
        f"                MapId = {cs_string(data['map_id'])},",
        f"                SizeMeters = {cs_point(data['size_m'])},",
    ]

    spawn_rows = []
    for s in sorted(data["spawn_sectors"], key=lambda x: x["team_slot"]):
        spawn_rows.append(
            "new RuntimeSpawnAnchor("
            f"{cs_string(s['spawn_id'])}, {int(s['team_slot'])}, {cs_point(s['center'])}, {int(s['facing_deg'])}, {int(s['safe_radius_m'])}, "
            f"{cs_points(s['initial_build_polygon'])}, {cs_points(s['rally_points'])})"
        )
    lines.append("                Spawns = new RuntimeSpawnAnchor[]")
    lines.append("                {")
    lines.extend(f"                    {row}," for row in spawn_rows)
    lines.append("                },")

    lines.append("                Resources = new RuntimeResourceAnchor[]")
    lines.append("                {")
    for n in sorted(data["resource_nodes"], key=lambda x: x["node_id"]):
        lines.append(
            "                    new RuntimeResourceAnchor("
            f"{cs_string(n['node_id'])}, {cs_string(n['resource_class'])}, {cs_string(n['mineral_id'])}, {cs_point(n['position'])}, "
            f"{int(n['capacity'])}L, {int(n['base_income_rate'])}, {int(n['extraction_slots'])}, {cs_string(n['control_region_id'])}),"
        )
    lines.append("                },")

    lines.append("                StrategicSites = new RuntimeStrategicSiteAnchor[]")
    lines.append("                {")
    for s in sorted(data["strategic_sites"], key=lambda x: x["site_id"]):
        lines.append(
            "                    new RuntimeStrategicSiteAnchor("
            f"{cs_string(s['site_id'])}, {cs_string(s['site_type'])}, {cs_point(s['position'])}, {cs_string(s['control_region_id'])}),"
        )
    lines.append("                },")

    lines.append("                Roads = new RuntimeRoad[]")
    lines.append("                {")
    for r in sorted(data["roads"], key=lambda x: x["road_id"]):
        permille = round(float(r["terrain_cost_multiplier"]) * 1000)
        lines.append(
            "                    new RuntimeRoad("
            f"{cs_string(r['road_id'])}, {cs_points(r['spline_points'])}, {int(r['width_m'])}, {permille}),"
        )
    lines.append("                },")

    lines.append("                BuildableAreas = new RuntimePolygonArea[]")
    lines.append("                {")
    for a in sorted(data["buildable_polygons"], key=lambda x: x["build_id"]):
        lines.append(
            "                    new RuntimePolygonArea("
            f"{cs_string(a['build_id'])}, {int(a['team_slot'])}, {cs_points(a['polygon'])}),"
        )
    lines.append("                },")

    lines.append("                ControlRegions = new RuntimeControlRegion[]")
    lines.append("                {")
    for r in sorted(data["control_regions"], key=lambda x: x["region_id"]):
        weight = round(float(r["strategic_weight"]) * 1000)
        neighbors = sorted(r["neighbors"])
        lines.append(
            "                    new RuntimeControlRegion("
            f"{cs_string(r['region_id'])}, {cs_points(r['polygon'])}, {cs_strings(neighbors)}, {weight}),"
        )
    lines.append("                },")

    rulesets = sorted(data["ruleset_compatibility"])
    lines.append(f"                RulesetCompatibility = {cs_strings(rulesets)}")
    lines += [
        "            };",
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate compile-time runtime map data for Unity and headless rules")
    parser.add_argument("--map", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()
    data = json.loads(args.map.read_text(encoding="utf-8"))
    source = generate_source(data)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(source, encoding="utf-8")
    print("RUNTIME MAP CODEGEN PASSED")
    print(f"map={data['map_id']} source_sha256={canonical_sha256(data)} bytes={len(source.encode('utf-8'))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
